// flow-typed signature: 6a54706ee20125d178ae0574602d66a1
// flow-typed version: <<STUB>>/humanize-number_v^0.0.2/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'humanize-number'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'humanize-number' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'humanize-number/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'humanize-number/index' {
  declare module.exports: $Exports<'humanize-number'>;
}
declare module 'humanize-number/index.js' {
  declare module.exports: $Exports<'humanize-number'>;
}
declare module 'humanize-number/test/index.js' {
  declare module.exports: $Exports<'humanize-number/test/index'>;
}
