// flow-typed signature: 8a79d3beb3f4afd7d783bda6627ad161
// flow-typed version: <<STUB>>/rosnodejs_v^2.1.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rosnodejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rosnodejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rosnodejs/dist/examples/on_the_fly' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/examples/standard' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/examples/turtle' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/index' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/lib/ActionClient' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/lib/impl/PublisherImpl' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/lib/impl/SubscriberImpl' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/lib/Logging' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/lib/MasterApiClient' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/lib/NodeHandle' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/lib/ParamServerApiClient' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/lib/Publisher' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/lib/RosNode' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/lib/ServiceClient' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/lib/ServiceServer' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/lib/SlaveApiClient' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/lib/Subscriber' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/lib/Time' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/ros_msg_utils/index' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/ros_msg_utils/lib/base_deserialize' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/ros_msg_utils/lib/base_serialize' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/ros_msg_utils/lib/encoding_utils' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/ros_msg_utils/lib/message_cache' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/ros_msg_utils/test/deserialization_test' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/ros_msg_utils/test/directory' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/ros_msg_utils/test/serialization_test' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/tools/flatten' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/tools/generateMessages' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/ClientStates' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/event_utils' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/log/ConsoleLogStream' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/log/LogFormatter' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/log/Logger' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/log/RosLogStream' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/message_utils' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/messageGeneration/fields' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/messageGeneration/IndentedWriter' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/messageGeneration/MessageLoader' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/messageGeneration/messages' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/messageGeneration/MessageSpec' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/messageGeneration/MessageWriter' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/messageGeneration/packages' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/namespace_utils' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/network_utils' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/serialization_utils' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/spinners/ClientQueue' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/spinners/GlobalSpinner' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/tcpros_utils' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/time_utils' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/xmlrpc_utils' {
  declare module.exports: any;
}

declare module 'rosnodejs/dist/utils/XmlrpcClient' {
  declare module.exports: any;
}

declare module 'rosnodejs/test/DeserializeStream' {
  declare module.exports: any;
}

declare module 'rosnodejs/test/directory' {
  declare module.exports: any;
}

declare module 'rosnodejs/test/gennodejsTest' {
  declare module.exports: any;
}

declare module 'rosnodejs/test/Log' {
  declare module.exports: any;
}

declare module 'rosnodejs/test/namespaceTest' {
  declare module.exports: any;
}

declare module 'rosnodejs/test/onTheFly' {
  declare module.exports: any;
}

declare module 'rosnodejs/test/onTheFlyMessages' {
  declare module.exports: any;
}

declare module 'rosnodejs/test/perfTest' {
  declare module.exports: any;
}

declare module 'rosnodejs/test/SpinnerTest' {
  declare module.exports: any;
}

declare module 'rosnodejs/test/stress' {
  declare module.exports: any;
}

declare module 'rosnodejs/test/utils/MasterStub' {
  declare module.exports: any;
}

declare module 'rosnodejs/test/xmlrpcTest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rosnodejs/dist/examples/on_the_fly.js' {
  declare module.exports: $Exports<'rosnodejs/dist/examples/on_the_fly'>;
}
declare module 'rosnodejs/dist/examples/standard.js' {
  declare module.exports: $Exports<'rosnodejs/dist/examples/standard'>;
}
declare module 'rosnodejs/dist/examples/turtle.js' {
  declare module.exports: $Exports<'rosnodejs/dist/examples/turtle'>;
}
declare module 'rosnodejs/dist/index.js' {
  declare module.exports: $Exports<'rosnodejs/dist/index'>;
}
declare module 'rosnodejs/dist/lib/ActionClient.js' {
  declare module.exports: $Exports<'rosnodejs/dist/lib/ActionClient'>;
}
declare module 'rosnodejs/dist/lib/impl/PublisherImpl.js' {
  declare module.exports: $Exports<'rosnodejs/dist/lib/impl/PublisherImpl'>;
}
declare module 'rosnodejs/dist/lib/impl/SubscriberImpl.js' {
  declare module.exports: $Exports<'rosnodejs/dist/lib/impl/SubscriberImpl'>;
}
declare module 'rosnodejs/dist/lib/Logging.js' {
  declare module.exports: $Exports<'rosnodejs/dist/lib/Logging'>;
}
declare module 'rosnodejs/dist/lib/MasterApiClient.js' {
  declare module.exports: $Exports<'rosnodejs/dist/lib/MasterApiClient'>;
}
declare module 'rosnodejs/dist/lib/NodeHandle.js' {
  declare module.exports: $Exports<'rosnodejs/dist/lib/NodeHandle'>;
}
declare module 'rosnodejs/dist/lib/ParamServerApiClient.js' {
  declare module.exports: $Exports<'rosnodejs/dist/lib/ParamServerApiClient'>;
}
declare module 'rosnodejs/dist/lib/Publisher.js' {
  declare module.exports: $Exports<'rosnodejs/dist/lib/Publisher'>;
}
declare module 'rosnodejs/dist/lib/RosNode.js' {
  declare module.exports: $Exports<'rosnodejs/dist/lib/RosNode'>;
}
declare module 'rosnodejs/dist/lib/ServiceClient.js' {
  declare module.exports: $Exports<'rosnodejs/dist/lib/ServiceClient'>;
}
declare module 'rosnodejs/dist/lib/ServiceServer.js' {
  declare module.exports: $Exports<'rosnodejs/dist/lib/ServiceServer'>;
}
declare module 'rosnodejs/dist/lib/SlaveApiClient.js' {
  declare module.exports: $Exports<'rosnodejs/dist/lib/SlaveApiClient'>;
}
declare module 'rosnodejs/dist/lib/Subscriber.js' {
  declare module.exports: $Exports<'rosnodejs/dist/lib/Subscriber'>;
}
declare module 'rosnodejs/dist/lib/Time.js' {
  declare module.exports: $Exports<'rosnodejs/dist/lib/Time'>;
}
declare module 'rosnodejs/dist/ros_msg_utils/index.js' {
  declare module.exports: $Exports<'rosnodejs/dist/ros_msg_utils/index'>;
}
declare module 'rosnodejs/dist/ros_msg_utils/lib/base_deserialize.js' {
  declare module.exports: $Exports<'rosnodejs/dist/ros_msg_utils/lib/base_deserialize'>;
}
declare module 'rosnodejs/dist/ros_msg_utils/lib/base_serialize.js' {
  declare module.exports: $Exports<'rosnodejs/dist/ros_msg_utils/lib/base_serialize'>;
}
declare module 'rosnodejs/dist/ros_msg_utils/lib/encoding_utils.js' {
  declare module.exports: $Exports<'rosnodejs/dist/ros_msg_utils/lib/encoding_utils'>;
}
declare module 'rosnodejs/dist/ros_msg_utils/lib/message_cache.js' {
  declare module.exports: $Exports<'rosnodejs/dist/ros_msg_utils/lib/message_cache'>;
}
declare module 'rosnodejs/dist/ros_msg_utils/test/deserialization_test.js' {
  declare module.exports: $Exports<'rosnodejs/dist/ros_msg_utils/test/deserialization_test'>;
}
declare module 'rosnodejs/dist/ros_msg_utils/test/directory.js' {
  declare module.exports: $Exports<'rosnodejs/dist/ros_msg_utils/test/directory'>;
}
declare module 'rosnodejs/dist/ros_msg_utils/test/serialization_test.js' {
  declare module.exports: $Exports<'rosnodejs/dist/ros_msg_utils/test/serialization_test'>;
}
declare module 'rosnodejs/dist/tools/flatten.js' {
  declare module.exports: $Exports<'rosnodejs/dist/tools/flatten'>;
}
declare module 'rosnodejs/dist/tools/generateMessages.js' {
  declare module.exports: $Exports<'rosnodejs/dist/tools/generateMessages'>;
}
declare module 'rosnodejs/dist/utils/ClientStates.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/ClientStates'>;
}
declare module 'rosnodejs/dist/utils/event_utils.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/event_utils'>;
}
declare module 'rosnodejs/dist/utils/log/ConsoleLogStream.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/log/ConsoleLogStream'>;
}
declare module 'rosnodejs/dist/utils/log/LogFormatter.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/log/LogFormatter'>;
}
declare module 'rosnodejs/dist/utils/log/Logger.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/log/Logger'>;
}
declare module 'rosnodejs/dist/utils/log/RosLogStream.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/log/RosLogStream'>;
}
declare module 'rosnodejs/dist/utils/message_utils.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/message_utils'>;
}
declare module 'rosnodejs/dist/utils/messageGeneration/fields.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/messageGeneration/fields'>;
}
declare module 'rosnodejs/dist/utils/messageGeneration/IndentedWriter.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/messageGeneration/IndentedWriter'>;
}
declare module 'rosnodejs/dist/utils/messageGeneration/MessageLoader.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/messageGeneration/MessageLoader'>;
}
declare module 'rosnodejs/dist/utils/messageGeneration/messages.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/messageGeneration/messages'>;
}
declare module 'rosnodejs/dist/utils/messageGeneration/MessageSpec.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/messageGeneration/MessageSpec'>;
}
declare module 'rosnodejs/dist/utils/messageGeneration/MessageWriter.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/messageGeneration/MessageWriter'>;
}
declare module 'rosnodejs/dist/utils/messageGeneration/packages.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/messageGeneration/packages'>;
}
declare module 'rosnodejs/dist/utils/namespace_utils.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/namespace_utils'>;
}
declare module 'rosnodejs/dist/utils/network_utils.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/network_utils'>;
}
declare module 'rosnodejs/dist/utils/serialization_utils.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/serialization_utils'>;
}
declare module 'rosnodejs/dist/utils/spinners/ClientQueue.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/spinners/ClientQueue'>;
}
declare module 'rosnodejs/dist/utils/spinners/GlobalSpinner.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/spinners/GlobalSpinner'>;
}
declare module 'rosnodejs/dist/utils/tcpros_utils.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/tcpros_utils'>;
}
declare module 'rosnodejs/dist/utils/time_utils.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/time_utils'>;
}
declare module 'rosnodejs/dist/utils/xmlrpc_utils.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/xmlrpc_utils'>;
}
declare module 'rosnodejs/dist/utils/XmlrpcClient.js' {
  declare module.exports: $Exports<'rosnodejs/dist/utils/XmlrpcClient'>;
}
declare module 'rosnodejs/test/DeserializeStream.js' {
  declare module.exports: $Exports<'rosnodejs/test/DeserializeStream'>;
}
declare module 'rosnodejs/test/directory.js' {
  declare module.exports: $Exports<'rosnodejs/test/directory'>;
}
declare module 'rosnodejs/test/gennodejsTest.js' {
  declare module.exports: $Exports<'rosnodejs/test/gennodejsTest'>;
}
declare module 'rosnodejs/test/Log.js' {
  declare module.exports: $Exports<'rosnodejs/test/Log'>;
}
declare module 'rosnodejs/test/namespaceTest.js' {
  declare module.exports: $Exports<'rosnodejs/test/namespaceTest'>;
}
declare module 'rosnodejs/test/onTheFly.js' {
  declare module.exports: $Exports<'rosnodejs/test/onTheFly'>;
}
declare module 'rosnodejs/test/onTheFlyMessages.js' {
  declare module.exports: $Exports<'rosnodejs/test/onTheFlyMessages'>;
}
declare module 'rosnodejs/test/perfTest.js' {
  declare module.exports: $Exports<'rosnodejs/test/perfTest'>;
}
declare module 'rosnodejs/test/SpinnerTest.js' {
  declare module.exports: $Exports<'rosnodejs/test/SpinnerTest'>;
}
declare module 'rosnodejs/test/stress.js' {
  declare module.exports: $Exports<'rosnodejs/test/stress'>;
}
declare module 'rosnodejs/test/utils/MasterStub.js' {
  declare module.exports: $Exports<'rosnodejs/test/utils/MasterStub'>;
}
declare module 'rosnodejs/test/xmlrpcTest.js' {
  declare module.exports: $Exports<'rosnodejs/test/xmlrpcTest'>;
}
